version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=amazon
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
      expose:
        - "5432"
  web:
      build: ./mini-amazon
      command: bash -c "poetry run ./install.sh && flask run"
      volumes:
        - ./mini-amazon:/code
      expose:
        - "8080"
      depends_on:
        - db
  amazon:
      build: ./server
      command: bash -c "python3 ./server.py"
      depends_on:
        - db
        - web